require 'spec_helper'

describe Opportunity do
  it "should respond to the column names" do
    Opportunity.should_receive(:acronym=         )
    Opportunity.should_receive(:program           )
    Opportunity.should_receive(:department        )
    Opportunity.should_receive(:agency            )
    Opportunity.should_receive(:description       )
    Opportunity.should_receive(:location          )
    Opportunity.should_receive(:input_record_id   )
    Opportunity.should_receive(:total_value       )
    Opportunity.should_receive(:win_probability   )
    Opportunity.should_receive(:contract_length   )
    Opportunity.should_receive(:solicitation_type )
    Opportunity.should_receive(:contract_type     )
    Opportunity.should_receive(:rfp_release_date  )
    Opportunity.should_receive(:rfp_due_date      )
    Opportunity.should_receive(:award_date        )
    Opportunity.should_receive(:prime             )
    Opportunity.should_receive(:capture_phase     )
    Opportunity.should_receive(:owner_id          )
    Opportunity.should_receive(:created_at        )
    Opportunity.should_receive(:updated_at        )
    Opportunity.should_receive(:input_status      )
    Opportunity.should_receive(:acquisition_url   )
    Opportunity.should_receive(:outcome           )
    Opportunity.should_receive(:our_value         )
  end
#  it "should respond to the column names" do
#    opp = mock_model(Opportunity)
#    opp.should_receive(:acronym           )
#    opp.should_receive(:program           )
#    opp.should_receive(:department        )
#    opp.should_receive(:agency            )
#    opp.should_receive(:description       )
#    opp.should_receive(:location          )
#    opp.should_receive(:input_record_id   )
#    opp.should_receive(:total_value       )
#    opp.should_receive(:win_probability   )
#    opp.should_receive(:contract_length   )
#    opp.should_receive(:solicitation_type )
#    opp.should_receive(:contract_type     )
#    opp.should_receive(:rfp_release_date  )
#    opp.should_receive(:rfp_due_date      )
#    opp.should_receive(:award_date        )
#    opp.should_receive(:prime             )
#    opp.should_receive(:capture_phase     )
#    opp.should_receive(:owner_id          )
#    opp.should_receive(:created_at        )
#    opp.should_receive(:updated_at        )
#    opp.should_receive(:input_status      )
#    opp.should_receive(:acquisition_url   )
#    opp.should_receive(:outcome           )
#    opp.should_receive(:our_value         )
#  end
end
